### ISSUE TITLE
Format a number

### ISSUE THREAD

**Issue by Newbie012** [AmitMY/js-prototypes#1]
Format a number would be a nice touch.

For example `1234.56 = 1,234.56`

**Comment by AmitMY** [comment]
The prototype you wish for already exists.
[`numObj.toLocaleString([locales [, options]])`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)

It even supports different locals, for different numbering systems (as some people write like this: 1.234,56), and for languages that have their own digits, like Arabic.
